import { execFileSync } from 'node:child_process';
import { readFile } from 'node:fs/promises';
const target=JSON.parse(await readFile(new URL('../deploy/target.json',import.meta.url)));
const run=(command,args,options={})=>execFileSync(command,args,{encoding:'utf8',stdio:['pipe','pipe','inherit'],...options});
if(run('git',['status','--porcelain']).trim())throw new Error('DEPLOY_DIRTY: 未commitの変更があります');
run('git',['fetch','origin',target.branch]);
const revision=(process.argv[2]??run('git',['rev-parse','HEAD'])).trim();
if(!/^[0-9a-f]{40}$/.test(revision))throw new Error('DEPLOY_REVISION_INVALID: 40桁のcommitを指定してください');
run('git',['merge-base','--is-ancestor',revision,`origin/${target.branch}`]);
const remote=await readFile(new URL('../deploy/remote.py',import.meta.url),'utf8');
const config=JSON.stringify({...target,revision});
const input=`import json\nTARGET=json.loads(${JSON.stringify(config)})\n${remote}`;
run('ssh',[target.sshHost,'python3 -'],{input,stdio:['pipe','inherit','inherit']});
